"""Decision emails in the recipient's language, including plain-text fallback.

Reviewer notes are user content and are never translated. Keep placeholders
and keys identical across the seven supported languages.
"""

COPY = {
    'en': {
        'brand': 'Citizen Science',
        'support': 'Questions? Reach us at',
        'project_approved_subject': 'Your project {project} was approved',
        'project_approved_body': 'Good news! "{project}" was approved and now has a public landing page on the Citizen Science Portal. You are its project manager.',
        'project_rejected_subject': 'About your project {project}',
        'project_rejected_body': 'Your project request "{project}" was not approved.',
        'project_footer': 'You receive this email because you proposed a project.',
        'project_cta': 'View project',
        'join_approved_subject': 'You joined {project}',
        'join_approved_body': 'Your request to join "{project}" was approved. You can now contribute through the Citizen Science Toolbox.',
        'join_rejected_subject': 'About your request to join {project}',
        'join_rejected_body': 'Your request to join "{project}" was not approved this time.',
        'join_footer': 'You receive this email because you requested to join a project.',
        'manager_approved_subject': 'Your UNESCO Citizen Science account was approved',
        'manager_approved_body': 'Good news! Your Project Manager account has been approved.\n\nYou can now log in and propose a citizen science project.',
        'manager_rejected_subject': 'About your UNESCO Citizen Science account',
        'manager_rejected_body': 'Your Project Manager account request was not approved at this time.',
        'manager_footer': 'You receive this email because you requested a Project Manager account.',
        'reviewer_note': 'Reviewer note: {reason}',
        'reason_not_provided': 'No reason was provided.',
    },
    'es': {
        'brand': 'Ciencia Ciudadana',
        'support': '¿Tienes preguntas? Escríbenos a',
        'project_approved_subject': 'Tu proyecto {project} fue aprobado',
        'project_approved_body': '¡Buenas noticias! "{project}" fue aprobado y ahora tiene una página pública en el Portal de Ciencia Ciudadana. Eres su gestor de proyecto.',
        'project_rejected_subject': 'Acerca de tu proyecto {project}',
        'project_rejected_body': 'Tu solicitud de proyecto "{project}" no fue aprobada.',
        'project_footer': 'Recibes este correo porque propusiste un proyecto.',
        'project_cta': 'Ver proyecto',
        'join_approved_subject': 'Te uniste a {project}',
        'join_approved_body': 'Tu solicitud para unirte a "{project}" fue aprobada. Ya puedes contribuir a través de la Caja de Herramientas de Ciencia Ciudadana.',
        'join_rejected_subject': 'Acerca de tu solicitud para unirte a {project}',
        'join_rejected_body': 'Tu solicitud para unirte a "{project}" no fue aprobada en esta ocasión.',
        'join_footer': 'Recibes este correo porque solicitaste unirte a un proyecto.',
        'manager_approved_subject': 'Tu cuenta de Ciencia Ciudadana de la UNESCO fue aprobada',
        'manager_approved_body': '¡Buenas noticias! Tu cuenta de gestor de proyectos fue aprobada.\n\nYa puedes iniciar sesión y proponer un proyecto de ciencia ciudadana.',
        'manager_rejected_subject': 'Acerca de tu cuenta de Ciencia Ciudadana de la UNESCO',
        'manager_rejected_body': 'Tu solicitud de cuenta de gestor de proyectos no fue aprobada en esta ocasión.',
        'manager_footer': 'Recibes este correo porque solicitaste una cuenta de gestor de proyectos.',
        'reviewer_note': 'Nota de revisión: {reason}',
        'reason_not_provided': 'No se proporcionó un motivo.',
    },
    'fr': {
        'brand': 'Science citoyenne',
        'support': 'Des questions ? Contactez-nous à',
        'project_approved_subject': 'Votre projet {project} a été approuvé',
        'project_approved_body': 'Bonne nouvelle ! Le projet "{project}" a été approuvé et dispose désormais d’une page publique sur le Portail de science citoyenne. Vous en êtes le gestionnaire.',
        'project_rejected_subject': 'À propos de votre projet {project}',
        'project_rejected_body': 'Votre demande de projet "{project}" n’a pas été approuvée.',
        'project_footer': 'Vous recevez cet e-mail parce que vous avez proposé un projet.',
        'project_cta': 'Voir le projet',
        'join_approved_subject': 'Vous avez rejoint {project}',
        'join_approved_body': 'Votre demande pour rejoindre "{project}" a été approuvée. Vous pouvez désormais contribuer via la Boîte à outils de science citoyenne.',
        'join_rejected_subject': 'À propos de votre demande pour rejoindre {project}',
        'join_rejected_body': 'Votre demande pour rejoindre "{project}" n’a pas été approuvée cette fois-ci.',
        'join_footer': 'Vous recevez cet e-mail parce que vous avez demandé à rejoindre un projet.',
        'manager_approved_subject': 'Votre compte de science citoyenne de l’UNESCO a été approuvé',
        'manager_approved_body': 'Bonne nouvelle ! Votre compte de gestionnaire de projets a été approuvé.\n\nVous pouvez désormais vous connecter et proposer un projet de science citoyenne.',
        'manager_rejected_subject': 'À propos de votre compte de science citoyenne de l’UNESCO',
        'manager_rejected_body': 'Votre demande de compte de gestionnaire de projets n’a pas été approuvée cette fois-ci.',
        'manager_footer': 'Vous recevez cet e-mail parce que vous avez demandé un compte de gestionnaire de projets.',
        'reviewer_note': 'Note de l’équipe de révision : {reason}',
        'reason_not_provided': 'Aucun motif n’a été fourni.',
    },
    'pt': {
        'brand': 'Ciência Cidadã',
        'support': 'Tem dúvidas? Contacte-nos em',
        'project_approved_subject': 'O seu projeto {project} foi aprovado',
        'project_approved_body': 'Boas notícias! "{project}" foi aprovado e já tem uma página pública no Portal de Ciência Cidadã. É o gestor deste projeto.',
        'project_rejected_subject': 'Sobre o seu projeto {project}',
        'project_rejected_body': 'O seu pedido de projeto "{project}" não foi aprovado.',
        'project_footer': 'Recebe este e-mail porque propôs um projeto.',
        'project_cta': 'Ver projeto',
        'join_approved_subject': 'Juntou-se a {project}',
        'join_approved_body': 'O seu pedido para participar em "{project}" foi aprovado. Já pode contribuir através da Caixa de Ferramentas de Ciência Cidadã.',
        'join_rejected_subject': 'Sobre o seu pedido para participar em {project}',
        'join_rejected_body': 'O seu pedido para participar em "{project}" não foi aprovado desta vez.',
        'join_footer': 'Recebe este e-mail porque pediu para participar num projeto.',
        'manager_approved_subject': 'A sua conta de Ciência Cidadã da UNESCO foi aprovada',
        'manager_approved_body': 'Boas notícias! A sua conta de gestor de projetos foi aprovada.\n\nJá pode iniciar sessão e propor um projeto de ciência cidadã.',
        'manager_rejected_subject': 'Sobre a sua conta de Ciência Cidadã da UNESCO',
        'manager_rejected_body': 'O seu pedido de conta de gestor de projetos não foi aprovado desta vez.',
        'manager_footer': 'Recebe este e-mail porque pediu uma conta de gestor de projetos.',
        'reviewer_note': 'Nota de revisão: {reason}',
        'reason_not_provided': 'Não foi indicado um motivo.',
    },
    'uk': {
        'brand': 'Громадянська наука',
        'support': 'Маєте запитання? Напишіть нам на',
        'project_approved_subject': 'Ваш проєкт {project} схвалено',
        'project_approved_body': 'Гарна новина! Проєкт "{project}" схвалено, і тепер він має публічну сторінку на Порталі громадянської науки. Ви є керівником цього проєкту.',
        'project_rejected_subject': 'Щодо вашого проєкту {project}',
        'project_rejected_body': 'Вашу заявку на проєкт "{project}" не схвалено.',
        'project_footer': 'Ви отримали цей лист, оскільки запропонували проєкт.',
        'project_cta': 'Переглянути проєкт',
        'join_approved_subject': 'Ви приєдналися до {project}',
        'join_approved_body': 'Ваш запит на приєднання до "{project}" схвалено. Тепер ви можете долучатися до роботи через Інструментарій громадянської науки.',
        'join_rejected_subject': 'Щодо вашого запиту на приєднання до {project}',
        'join_rejected_body': 'Цього разу ваш запит на приєднання до "{project}" не схвалено.',
        'join_footer': 'Ви отримали цей лист, оскільки подали запит на приєднання до проєкту.',
        'manager_approved_subject': 'Ваш обліковий запис громадянської науки ЮНЕСКО схвалено',
        'manager_approved_body': 'Гарна новина! Ваш обліковий запис керівника проєктів схвалено.\n\nТепер ви можете увійти та запропонувати проєкт громадянської науки.',
        'manager_rejected_subject': 'Щодо вашого облікового запису громадянської науки ЮНЕСКО',
        'manager_rejected_body': 'Цього разу вашу заявку на обліковий запис керівника проєктів не схвалено.',
        'manager_footer': 'Ви отримали цей лист, оскільки подали заявку на обліковий запис керівника проєктів.',
        'reviewer_note': 'Примітка рецензента: {reason}',
        'reason_not_provided': 'Причину не вказано.',
    },
    'ar': {
        'brand': 'علم المواطن',
        'support': 'هل لديك أسئلة؟ تواصل معنا على',
        'project_approved_subject': 'تمت الموافقة على مشروعك {project}',
        'project_approved_body': 'أخبار سارة! تمت الموافقة على "{project}" وأصبح له الآن صفحة عامة على بوابة علم المواطن. أنت مدير هذا المشروع.',
        'project_rejected_subject': 'بخصوص مشروعك {project}',
        'project_rejected_body': 'لم تتم الموافقة على طلب مشروعك "{project}".',
        'project_footer': 'تصلك هذه الرسالة لأنك اقترحت مشروعاً.',
        'project_cta': 'عرض المشروع',
        'join_approved_subject': 'لقد انضممت إلى {project}',
        'join_approved_body': 'تمت الموافقة على طلبك للانضمام إلى "{project}". يمكنك الآن المساهمة من خلال صندوق أدوات علم المواطن.',
        'join_rejected_subject': 'بخصوص طلبك للانضمام إلى {project}',
        'join_rejected_body': 'لم تتم الموافقة على طلبك للانضمام إلى "{project}" هذه المرة.',
        'join_footer': 'تصلك هذه الرسالة لأنك طلبت الانضمام إلى مشروع.',
        'manager_approved_subject': 'تمت الموافقة على حسابك في علم المواطن لدى اليونسكو',
        'manager_approved_body': 'أخبار سارة! تمت الموافقة على حسابك كمدير مشاريع.\n\nيمكنك الآن تسجيل الدخول واقتراح مشروع لعلم المواطن.',
        'manager_rejected_subject': 'بخصوص حسابك في علم المواطن لدى اليونسكو',
        'manager_rejected_body': 'لم تتم الموافقة على طلب حسابك كمدير مشاريع هذه المرة.',
        'manager_footer': 'تصلك هذه الرسالة لأنك طلبت حساب مدير مشاريع.',
        'reviewer_note': 'ملاحظة المراجع: {reason}',
        'reason_not_provided': 'لم يتم تقديم سبب.',
    },
    'quh': {
        'brand': 'Llaqta Runa Yachay',
        'support': 'Tapuykunayki kanchu? Kayman qillqawayku',
        'project_approved_subject': 'Wakichiyki {project} chiqanchasqaña',
        'project_approved_body': 'Allin willay! "{project}" chiqanchasqaña, kunanqa Llaqta Runa Yachay portalpi llapanpaq raphiyniyuqña. Qan kay wakichiypa kamachiqnin kanki.',
        'project_rejected_subject': 'Wakichiyki {project} nisqamanta',
        'project_rejected_body': '"{project}" wakichiy mañakuyniyki mana chiqanchasqachu.',
        'project_footer': 'Wakichiyta riqsichirqankirayku kay correo chaskinki.',
        'project_cta': 'Wakichiyta qhaway',
        'join_approved_subject': '{project} wakichiyman yaykurqanki',
        'join_approved_body': '"{project}" wakichiyman yaykunaykipaq mañakuyniyki chiqanchasqaña. Kunanqa Llaqta Runa Yachay Llamk’ana K’itipi yanapayta atinki.',
        'join_rejected_subject': '{project} wakichiyman yaykunaykipaq mañakuyniykimanta',
        'join_rejected_body': '"{project}" wakichiyman yaykunaykipaq mañakuyniyki kay kutipi mana chiqanchasqachu.',
        'join_footer': 'Wakichiyman yaykunaykipaq mañakurqankirayku kay correo chaskinki.',
        'manager_approved_subject': 'UNESCO Llaqta Runa Yachay cuentayki chiqanchasqaña',
        'manager_approved_body': 'Allin willay! Wakichiy kamachiq cuentayki chiqanchasqaña.\n\nKunanqa yaykuyta, llaqta runa yachay wakichiyta riqsichiyta ima atinki.',
        'manager_rejected_subject': 'UNESCO Llaqta Runa Yachay cuentaykimanta',
        'manager_rejected_body': 'Wakichiy kamachiq cuenta mañakuyniyki kay kutipi mana chiqanchasqachu.',
        'manager_footer': 'Wakichiy kamachiq cuentata mañakurqankirayku kay correo chaskinki.',
        'reviewer_note': 'Qhawariqpa willaynin: {reason}',
        'reason_not_provided': 'Mana imarayku kasqanta willakurqanchu.',
    },
}
